INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES ( 2,"Aguascalientes","Ags","AG","AGU");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES ( 3,"Baja California","BC","BC","BCN");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES ( 4,"Baja California Sur","BCS","BS","BCS");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES ( 5,"Campeche","Camp","CM","CAM");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES ( 6,"Chiapas","Chis","CS","CHP");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES ( 7,"Chihuahua","Chih","CH","CHH");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES ( 8,"Coahuila","Coah","CO","COA");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES ( 9,"Colima","Col","CL","COL");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (10,"Distrito Federal","DF","DF","DIF");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (11,"Durango","Dgo","DG","DUR");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (12,"Guanajuato","Gto","GT","GUA");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (13,"Guerrero","Gro","GR","GRO");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (14,"Hidalgo","Hgo","HG","HID");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (15,"Jalisco","Jal","JC","JAL");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (16,"Estado de Mexico","Mex","ME","MEX");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (17,"Michoacan","Mich","MN","MIC");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (18,"Morelos","Mor","MS","MOR");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (19,"Nayarit","Nay","NT","NAY");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (20,"Nuevo León","NL","NL","NLE");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (21,"Oaxaca","Oax","OC","AC");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (22,"Puebla","Pue","PL","PUE");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (23,"Querétaro","Qro","QO","QUE");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (24,"Quintana Roo","QRoo","QR","ROO");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (25,"San Luis Potosi","SLP","SP","SLP");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (26,"Sinaloa","Sin","SL","SIN");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (27,"Sonora","Son","SR","SON");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (28,"Tabasco","Tab","TC","TAB");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (29,"Tamaulipas","Tamps","TS","TAM");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (30,"Tlaxcala","Tlax","TL","TLA");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (31,"Veracruz","Ver","VZ","VER");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (32,"Yucatan","Yuc","YN","YUC");
INSERT INTO entidad (id,nombre,var,abr,abr3) VALUES (33,"Zacatecas","Zac","ZS","ZAC");
