CREATE TABLE entidad (
	id INTEGER PRIMARY KEY,
	nombre STRING,
	var STRING,
	abr STRING,
	abr3 STRING
);

CREATE TABLE summary (
	time_stamp STRING,
	date_stamp STRING,
	ACTAS_CAPTURADAS INTEGER, 
	ACTAS_POR_CAPTURAR INTEGER,
	PORCENTAJE_ACTAS_CAPTURADAS REAL, 
	ACTAS_CONTABILIZADAS INTEGER, 
	ACTAS_NO_CONTABILIZADAS INTEGER, 
	PARTICIPACION_CIUDADANA REAL
);

CREATE TABLE voto (
	ESTADO INTEGER, 
	DISTRITO INTEGER, 
	SECCION INTEGER, 
	ID_CASILLA INTEGER, 
	TIPO_CASILLA STRING, 
	EXT_CONTIGUA INTEGER, 
	UBICACION_CASILLA INTEGER, 
	TIPO_ACTA INTEGER, 
	PAN INTEGER, 
	PRI INTEGER, 
	PRD INTEGER, 
	PVEM INTEGER, 
	PT INTEGER, 
	MC INTEGER, 
	PANAL INTEGER, 
	C_PRI_PVEM INTEGER, 
	C_PRD_PT_MC INTEGER, 
	C_PRD_PT INTEGER, 
	C_PRD_MC INTEGER, 
	C_PT_MC INTEGER, 
	NO_REGISTRADOS INTEGER, 
	NULOS INTEGER, 
	TOTAL_VOTOS INTEGER, 
	LISTA_NOMINAL INTEGER, 
	OBSERVACIONES INTEGER, 
	CONTABILIZADA INTEGER, 
	CRYT INTEGER, 
	HORA_ACOPIO DATE, 
	HORA_CAPTURA DATE, 
	HORA_REGISTRO DATE
);
